services:
  - type: web
    name: blitzapp
    env: node
    plan: Starter Plus
    buildCommand: yarn --frozen-lockfile --prod=false; blitz prisma migrate save --experimental; blitz prisma migrate up --experimental; blitz build
    # If you have an out of memory error, change startCommand to "yarn next start"
    startCommand: yarn next start # blitz start --production
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blitzapp-db
          property: connectionString
databases:
  - name: blitzapp-db
    plan: starter
